### ISSUE TITLE
داخل صفحه ادیتور به دنیای سلام خوش امدی اینجا دیگه هیچ محدودیتی نداره بنظرم فقط وقتی ظاهر باشه که هنوز هیچ کلیدی زده نشده به محض اینکه کلیدی زده میشه و ادیتور نمایان میشه دیگه اون سکشن نارنجی زیر هدر کلا مخفی بشه چون تمرکز روی ادیتور باشه بهتره. بخصوص برای موبایل چون بهتره اینطوری

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#100]
داخل صفحه ادیتور به دنیای سلام خوش امدی اینجا دیگه هیچ محدودیتی نداره بنظرم فقط وقتی ظاهر باشه که هنوز هیچ کلیدی زده نشده به محض اینکه کلیدی زده میشه و ادیتور نمایان میشه دیگه اون سکشن نارنجی زیر هدر کلا مخفی بشه چون تمرکز روی ادیتور باشه بهتره. بخصوص برای موبایل چون بهتره اینطوری

![image](https://github.com/user-attachments/assets/98d1331d-760e-4b6d-ae2b-31f8bb7a71ae)
![image](https://github.com/user-attachments/assets/dd5a3f72-4646-417e-b464-79ca84590602)

**Comment by BaseMax** [comment]
![image](https://github.com/user-attachments/assets/91ab005e-8e9d-4877-9088-2fb63734928d)
![image](https://github.com/user-attachments/assets/5449f0fe-805c-4c6c-ac40-93188b7f8484)


خوب شده نسخه جدیده

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/853c2951-f9e6-42c3-abc0-ccf405c4bbcd)
![image](https://github.com/user-attachments/assets/319e36db-9737-42dc-a55b-a41e93bb95e7)
