### ISSUE TITLE
صفحه ادیتور دکمه ران که داریم وقتی روش میزنن از حالت ران خارج بشه لودینگ داخلش بچرخه و دکمه غیر قابل کلیک بشه و بعد از یک ثانیه تاخیر خروجی از پایین ظاهر بشه. الان فوری بلافاصله خروجی از پایین ظاهر میشه بنظرم به این یکم تاخیر فیک بدیم که لودینگ و حالت غیر قابل کلیک بودن دکمه هم کامل هندل کنید. دلیل اینکار اینه که اجرا شدن برنامه چندین ثانیه زمان میبره تا اجرا بشه و خروجی ساخته بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#101]
صفحه ادیتور دکمه ران که داریم وقتی روش میزنن از حالت ران خارج بشه لودینگ داخلش بچرخه و دکمه غیر قابل کلیک بشه و بعد از یک ثانیه تاخیر خروجی از پایین ظاهر بشه. الان فوری بلافاصله خروجی از پایین ظاهر میشه بنظرم به این یکم تاخیر فیک بدیم که لودینگ و حالت غیر قابل کلیک بودن دکمه هم کامل هندل کنید. دلیل اینکار اینه که اجرا شدن برنامه چندین ثانیه زمان میبره تا اجرا بشه و خروجی ساخته بشه

![image](https://github.com/user-attachments/assets/5e881146-63c4-419c-b563-00e4801c9ee7)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/22589d63-4d0e-404b-9be0-3bb1a2e0d95e)
