### ISSUE TITLE
داخل صفحه ادیتور باگ داریم ای فریم اجرا و مودال ها که باز میشن قاطی میشه. بنظرم الویت مودال ها بیشتر از ای فریم اجرا هست و باید ای فریم اجرا زیر مودال ها بمونه ولی الان اینطوری نیست

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#102]
داخل صفحه ادیتور باگ داریم ای فریم اجرا و مودال ها که باز میشن قاطی میشه. بنظرم الویت مودال ها بیشتر از ای فریم اجرا هست و باید ای فریم اجرا زیر مودال ها بمونه ولی الان اینطوری نیست

![image](https://github.com/user-attachments/assets/bc775208-8b40-40a4-8d82-c299f9e46218)

**Comment by ali-josheghani** [comment]
fixed

![image](https://github.com/user-attachments/assets/a58c939c-45c9-4f2a-85c4-fbc09062d507)
