### ISSUE TITLE
صفحه ۴۰۴ ما چرا فونتش کلا پریده و فونت لود نمیکنه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#104]
صفحه ۴۰۴ ما چرا فونتش کلا پریده و فونت لود نمیکنه

![image](https://github.com/user-attachments/assets/c730d0f7-92df-4a55-8763-19082e7eb467)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/b8d0e217-a4a8-4dac-8730-66078ae90b43)
برا من کار میکنه
