### ISSUE TITLE
خیلی از لینک ها داره لینک میشه به صفحه ۴۰۴ که اشتباهه بزن بریم ها رو یا به صفحه ادیتور لینک کنید یا به صفحه دانلود

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#105]
خیلی از لینک ها داره لینک میشه به صفحه ۴۰۴ که اشتباهه بزن بریم ها رو یا به صفحه ادیتور لینک کنید یا به صفحه دانلود

![image](https://github.com/user-attachments/assets/4444f3ca-d84c-4068-80b5-320a03c74585)

**Comment by ali-josheghani** [comment]
صفحه اصلی تمام دکمه ها لینک شدن

**Comment by ali-josheghani** [comment]
صفحه دانلود هم دکمه **مشاهده آموزش** به صفحه **education** لینک شد
