### ISSUE TITLE
صفحه دانلود باید وقتی ظاهر بشه که در صفحه اموزش یا در صفحه اصلی روی گزینه دانلود یک سیستم عامل زده شد. بنابراین داخل صفحه دانلود باید نوع سیستم عامل رو هم ورودی بگیریم.  اینطوری داخل صفحه دانلود پارامتر این رو داریم که چه سیستم عاملی هست هم کاربر رو هدایت می کنیم دانلودش داخل مروگر شروع بشه هم داخل صفحه تشکر کردیم بابت دانلود

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#106]
صفحه دانلود باید وقتی ظاهر بشه که در صفحه اموزش یا در صفحه اصلی روی گزینه دانلود یک سیستم عامل زده شد. بنابراین داخل صفحه دانلود باید نوع سیستم عامل رو هم ورودی بگیریم.  اینطوری داخل صفحه دانلود پارامتر این رو داریم که چه سیستم عاملی هست هم کاربر رو هدایت می کنیم دانلودش داخل مروگر شروع بشه هم داخل صفحه تشکر کردیم بابت دانلود

![image](https://github.com/user-attachments/assets/4a5975c9-a70f-443a-baa4-98eeaa362ed6)

![image](https://github.com/user-attachments/assets/c4d15562-1107-4223-8f6d-597f48a2374c)

![image](https://github.com/user-attachments/assets/403fd9ad-daed-43f0-8faf-da4bc592f4b0)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/5fd0f9e5-46aa-4313-9f8e-828042f2877a)

فعلا در حد توست نمایش میده برای چی سیستم عاملی درخواست داده

**Comment by ali-josheghani** [comment]
دکمه های دانلود هم لینک شدن

**Comment by BaseMax** [comment]
نباید بتونه چند بار پشت سر هم رو دکمه کلیک بکنه باید قفل بشه
