### ISSUE TITLE
مشکل صفحه کارت ها

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#107]
![Screenshot (6)](https://github.com/user-attachments/assets/0871a782-c701-46a3-9b44-57ee3c823942)
![Screenshot (7)](https://github.com/user-attachments/assets/c177bd7a-4150-419a-9ec4-c3cf589344d9)
این دو صفحه باهم متفاوت هستند مثلا یکی بکگراند داره اما دیگری نداره منظورم از ایندو صفحه صفحجه سایت و طرح است

**Comment by mohamadreza1388** [comment]
ایکون ها هم فرق داره

**Comment by ali-josheghani** [comment]
متوجه نمیشم

**Comment by ali-josheghani** [comment]
اگه منظورت تفاوت ظاهری بین ui و فرانت هست که اون در ایشو قبلی اوکی شده

**Comment by BaseMax** [comment]
اگه تمومه ببندید

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/44765233-23a8-4ec9-9b28-f475554e5a1c)
