### ISSUE TITLE
یکسری هشدار برای فایل های گیف داریم بررسی شود

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#108]
```
 GET / 200 in 583ms
 ○ Compiling /Playground ...
 ✓ Compiled /Education in 16.8s (2200 modules)
 ⚠ The requested resource "/_next/static/media/download.1d6629d7.gif" is an animated image so it will not be optimized. Consider adding the "unoptimized" property to the <Image>.
 ⚠ The requested resource "/_next/static/media/education2.c5232e28.gif" is an animated image so it will not be optimized. Consider adding the "unoptimized" property to the <Image>.
 ⚠ The requested resource "/_next/static/media/education.a7396da2.gif" is an animated image so it will not be optimized. Consider adding the "unoptimized" property to the <Image>.
 GET /Playground 200 in 271ms
 GET /Playground 200 in 100ms
 GET /Playground 200 in 64ms
 GET /Playground 200 in 119ms
 GET /Playground 200 in 82ms
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 1180ms (2193 modules)
 GET /404 404 in 451ms
 ⚠ The requested resource "/_next/static/media/404.7d7ca727.gif" is an animated image so it will not be optimized. Consider adding the "unoptimized" property to the <Image>.
 GET /404 404 in 60ms
 GET /dfgdfgdfg 404 in 114ms
 GET /dfgdfgdfg 404 in 95ms
 GET /404 404 in 99ms
 GET / 200 in 2594ms

```

**Comment by BaseMax** [comment]
بنظر میرسه که باید از تگ Image استفاده کرد برای اینجور چیز ها

**Comment by BaseMax** [comment]
𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/7/2024 2:24 PM]
از تگ Image استفاده شده

𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/7/2024 2:24 PM]
ولی نکست میگه

Max Base, [9/7/2024 2:24 PM]
unoptimized

Max Base, [9/7/2024 2:25 PM]
این رو باید به تصاویری که گیف هستند بدید.

𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/7/2024 2:25 PM]
از گیف استفاده نباید کرد

Max Base, [9/7/2024 2:25 PM]
اگه لینک یک تصویر گیف هست باید پروپرتی unoptimized بدید.

𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/7/2024 2:25 PM]
اره اتربیوتش

Max Base, [9/7/2024 2:25 PM]
چرا میشه گیف استفاده کرد ولی unoptimized بدید.

𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/7/2024 2:25 PM]
دقیقا همین کار کردم به هرحال

Max Base, [9/7/2024 2:25 PM]
یک ورودی true false بدید. پیشفرض هم false باشه. فقط اونجاها که گیف هست ترو پاس بدید اینور unoptimized رو اضافه کنید

Max Base, [9/7/2024 2:25 PM]
اوکی

**Comment by ali-josheghani** [comment]
✅
