### ISSUE TITLE
اسلایدر مشکل داره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#109]
طبق صحبتی که داشتم با مهند و اینا گفت که پیجینیشن نمیخاد اما خودکار حرکت کنه 
autoplay داشته باشه

**Comment by ali-josheghani** [comment]
کدوم اسلایدر دوتا اسلایدر داریم 
جفتش؟

**Comment by BaseMax** [comment]
اسلایدری که نظرات ادم ها زیاد هست و فلش چپ راست هم حتی نداره

**Comment by BaseMax** [comment]
![image](https://github.com/user-attachments/assets/d54aac04-42ea-4e84-af0a-640ed305c7e2)

**Comment by ali-josheghani** [comment]
auto play اضافه شد با 

با تاخیر **۲ ثانیه**

وقتی پوش شد چک شه و نیازی بود باز شه این ایشو
