### ISSUE TITLE
تصویر پس زمینه اوکی نیست

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#110]
تصویر پس زمینه فرق داره
رنگ پس زمینه هم همینطور
![Screenshot (12)](https://github.com/user-attachments/assets/5639bae3-086e-4f69-9525-990746f115ce)
![Screenshot (13)](https://github.com/user-attachments/assets/1a5dc958-878f-4149-af1b-00212c84667f)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/0963d1f5-7cf6-4070-92a5-d055464acf03)
