### ISSUE TITLE
رنگ فوتتر

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#112]
![Screenshot (16)](https://github.com/user-attachments/assets/31a6dbf2-ccc9-4e6a-a381-a4c00f286140)
رنگ فوتر کاملا با طرح فرق دارعه

**Comment by mohamadreza1388** [comment]
![Uploading Screenshot (17).png…]()

**Comment by BaseMax** [comment]
تصویر تصویر فیگما بوده میتونید فیگما رو چک کنید. تصویر دومش اپلود نشده کامل.
