### ISSUE TITLE
متن ها بزرگه

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#116]
![Uploading Screenshot (23).png…]()

**Comment by BaseMax** [comment]
بنظر عکس خراب شده و لود نمیشه
لطفا بیشتر توضیح بدید کجا و کدوم صفحه هست

**Comment by BaseMax** [comment]
بنظر میرسه اپلودت تموم نشده بوده که ایشو رو ارسال زدی. باید صبر میکردی کامل اپلود بشه

**Comment by mohamadreza1388** [comment]
چشم ارسال میکنم عکس رو

**Comment by mohamadreza1388** [comment]
عکس رو پیدا نکردم
