### ISSUE TITLE
توهم رفته

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#117]
![Screenshot (22)](https://github.com/user-attachments/assets/46814c74-a4cf-4b41-8b42-ef38731528f3)

**Comment by BaseMax** [comment]
نه خوب نیست.

**Comment by BaseMax** [comment]
در تلگرام گفتگو انجام شد.

**Comment by ali-josheghani** [comment]
فیکس نیاز بود دوباره باز بشه تشکر
