### ISSUE TITLE
فیلد موبایل

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#118]
![dsfsdfsadfasodpfiasdf](https://github.com/user-attachments/assets/e43975e3-384e-4a0d-bf8f-0c8e7c87aba3)

**Comment by BaseMax** [comment]
بنظر اون قسمت به درستی ریسپانسیو نشده و جای کار داره

**Comment by BaseMax** [comment]
پیام از شما:
تو گوشی اینجوری ریسپانسیو میشه
![image](https://github.com/user-attachments/assets/afc1d2c4-f5ce-4482-bd1c-3da6d20c1b16)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/44e2e619-3b0b-4a23-ba51-b52f0bac4834)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/52d7c0f2-4dd8-4a73-ba33-b67e07a8d735)
