### ISSUE TITLE
اسکرول صفحه

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#119]
یه مشکلی داریم که الان بهش برخوردم
![Screenshot (27)](https://github.com/user-attachments/assets/43369bcf-3970-41db-8e87-62f0fe2f69b2)
نمیشه توی صفحه اسکرول کرد
اسکرولش بستس
توی موبایل هم همینجوریه

**Comment by ali-josheghani** [comment]
مهندس گفته بودند اسکرول صفحه اصلی بسته شه 

فقط باکس ادیتور اسکرول از دو طرف داره یکی x یکی y

**Comment by mohamadreza1388** [comment]
اها اوکی
خب توی موبایل چی؟
باید اسکرول بخوره اخه

**Comment by mohamadreza1388** [comment]
میخواین ازش بپرسم؟؟

**Comment by ali-josheghani** [comment]
> میخواین ازش بپرسم؟؟

ok

**Comment by BaseMax** [comment]
بنظرم اره صفحه فول باشه نیاز به اسکرول نداره.
فقط تمرکز روی محیط نوشتن کد باشه

**Comment by BaseMax** [comment]
- ولی محتوا باید جوری چیده بشه که اصلا نیاز به اسکرول کردن صفحه نباشه
- فقط داخل کد ها بشه اسکرول کرد

**Comment by ali-josheghani** [comment]
ok

**Comment by ali-josheghani** [comment]
ایشو باز بمونه لطفا

**Comment by ali-josheghani** [comment]
قبلا فیکس شد و این صفحه رو جوری طراحی شد ک نیاز به اسکرول نباشه محتوا حتی تو موبایل 

فقط باکس کد ادیتور اسکرول میخوره

**Comment by ali-josheghani** [comment]
ایشو میبندم نیاز بود باز شه
