### ISSUE TITLE
وقتی روی دکمه میزنیم و نسخه با موفقیت تغییر میکنه باید مودال بسته بشه ولی وقتی تغییر نسخه به خطا میخوره مودال باید باز بمونه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#125]
وقتی روی دکمه میزنیم و نسخه با موفقیت تغییر میکنه باید مودال بسته بشه ولی وقتی تغییر نسخه به خطا میخوره مودال باید باز بمونه

![image](https://github.com/user-attachments/assets/0e6c8f79-3a7f-4265-9f31-b7a119ec2cfc)

**Comment by ali-josheghani** [comment]
fixed
