### ISSUE TITLE
مودال ها که باز میشوند چه مودال شیر و یا مودال تنظیمات باید الویت بالا باشه و حتی روی مودال ای فریم خروجی پایین قرار بگیره ولی الان ایکن پلی و ایفریم پاین امده روی مودال تنظیمات قرار گرفته

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#126]
مودال ها که باز میشوند چه مودال شیر و یا مودال تنظیمات باید الویت بالا باشه و حتی روی مودال ای فریم خروجی پایین قرار بگیره ولی الان ایکن پلی و ایفریم پاین امده روی مودال تنظیمات قرار گرفته

![image](https://github.com/user-attachments/assets/85f21f7e-8d3c-4e7a-9842-ba0b46a7d176)

**Comment by ali-josheghani** [comment]
fixed
