### ISSUE TITLE
درصفحه اصلی وقتی کاربر یکم اسکرول میکنه باید هدر دومی ظهر بشه و بچسبه به بالا و مجدد وقتی اسکرول کرد به بالا صفحه هدر دوم مخفی بشه و کاربر هدر اول رو ببینه البته هدر اول چسبان نیست و همیشه همون بالا مونده ولی هدر دوم تو صفحه اصلی وقتی ظاهر میشه باید چسبان باشه موقع ظاهر شدنش هم میشه افکت بدید از بالا بیادش

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#127]
درصفحه اصلی وقتی کاربر یکم اسکرول میکنه باید هدر دومی ظهر بشه و بچسبه به بالا و مجدد وقتی اسکرول کرد به بالا صفحه هدر دوم مخفی بشه و کاربر هدر اول رو ببینه البته هدر اول چسبان نیست و همیشه همون بالا مونده ولی هدر دوم تو صفحه اصلی وقتی ظاهر میشه باید چسبان باشه موقع ظاهر شدنش هم میشه افکت بدید از بالا بیادش

**Comment by ali-josheghani** [comment]
فقط صفحه اصلی دیگه؟

**Comment by BaseMax** [comment]
بله فقط صفحه اصلی

**Comment by BaseMax** [comment]
هدر نباید از راست و چپ بیاد فقط از بالا میاد پایین
و از پایین میره بالا

**Comment by ali-josheghani** [comment]
حله درست شد
