### ISSUE TITLE
صفحه اصلی در سکشن ادم ها که عکس داره تولتیب اش بنظرم بد ظاهر میشه بهتره انیمیشن ظاهر و مخفی شدنش رو بهبود بدیم تا بهتر و جذاب تر بشه. میشه از شتاب هم به خوبی کمک گرفت

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#132]
صفحه اصلی در سکشن ادم ها که عکس داره تولتیب اش بنظرم بد ظاهر میشه بهتره انیمیشن ظاهر و مخفی شدنش رو بهبود بدیم تا بهتر و جذاب تر بشه. میشه از شتاب هم به خوبی کمک گرفت

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/7f655a5a-7c1a-4e04-8d6a-dc34f0d1a4af)
✅
