### ISSUE TITLE
مشکل و اشتباه بودن تشهیص سیستم عامل

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#135]
در مک سهیل:
![image](https://github.com/user-attachments/assets/46250c19-691d-4d25-a2ed-e8d861f88443)

در ویندوز:
![image](https://github.com/user-attachments/assets/4302591b-0c55-42ec-ad4c-26f7b995e7ad)

در لینوکس خودتان:
![image](https://github.com/user-attachments/assets/aab67d3c-2813-42fb-b57a-75c330d2083d)

**Comment by ali-josheghani** [comment]
درست کار می کنه ✔️

**Comment by ali-josheghani** [comment]
فیکس شد
