### ISSUE TITLE
غیر از صفحه اصلی که عالی شده تو بقیه صفحه ها مثل اموزش و ... هم باید هدر وقتی پایین میری شناور بشه. 

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#136]
https://salamlang.ir/education

**Comment by BaseMax** [comment]
البته صفحه دانلود و صفحه 404 چون اسکرول نمیخوره این کامپوننت شاید کلا دیده نشه

**Comment by BaseMax** [comment]
توی صفحه ادیتور هم اسکرول نمیخوره دیده نمیشه.

ولی توی صفحه اموزش میشه

**Comment by ali-josheghani** [comment]
ok به layout صفحه education اضافه شد
