### ISSUE TITLE
دوتا دکمه نارجی رنگ لینک نیستند

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#141]
![Screenshot 2024-09-10 120418](https://github.com/user-attachments/assets/316d163d-efcd-4d5a-9776-1b0460b43a0e)
دوتا دکمه نارجی رنگ لینک نیستند

**Comment by ali-josheghani** [comment]
به صفحه پلی گراند لینک شد

**Comment by ali-josheghani** [comment]
یا همون ادیتور

**Comment by ali-josheghani** [comment]
نیاز بود دوباره باز  شه
