### ISSUE TITLE
دکمه حامی میشوم به جایی لینک نیست

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#142]
![Screenshot 2024-09-10 120703](https://github.com/user-attachments/assets/8d161510-4947-4c13-adf2-251f0758de6d)
دکمه حامی میشوم به جایی لینک نیست

**Comment by ali-josheghani** [comment]
فعلا تصمیمی برای این قسمت گرفته نشده ! 
پس باز بمونه این ایشو
