### ISSUE TITLE
نظرات لینک نیست

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#143]
![Screenshot 2024-09-10 120913](https://github.com/user-attachments/assets/7bab413c-0993-4730-ab8d-d82a0fcdacbe)
نظرات لینک نیست

**Comment by ali-josheghani** [comment]
این منو استاتیکه و باید مثل منوی اصلی لینک هاش یکی شن

**Comment by BaseMax** [comment]
داده های این طوری رو ارایه کنید const menu = []
از اون حلقه بزنید اینطوری سراسری هم میشه

**Comment by BaseMax** [comment]
اگه ایتم های منو رو دارید حلقه می کنید و به خوبی هندل شده ایشو رو ببندید اوکیه.

**Comment by BaseMax** [comment]
Max Base, [9/11/2024 10:02 AM]
اگه ایتم های منو رو دارید حلقه می کنید و به خوبی هندل شده ایشو رو ببندید اوکیه.

Max Base, [9/11/2024 10:05 AM]
اها بله هش مپ و ارایه هر کدوم بهتر بودند استفاده بشود.

Max Base, [9/11/2024 10:05 AM]
منظورم فقط این بوده متغییر بشه. اگه شده ببندید.
