### ISSUE TITLE
این بخش به کل کار نمیکنه

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#145]
![Screenshot 2024-09-10 121446](https://github.com/user-attachments/assets/b65f6263-8492-4e3b-ba0e-400efb864967)
این بخش به کل کار نمیکنه

**Comment by ali-josheghani** [comment]
سلام کار میکنه ولی کلاس های دارک براش تعبیه نشده هنوز 

این رو میبندم و ی ایشو بنام تکمیل دارک مود میسازم
