### ISSUE TITLE
این قسمت زیاد جالب نیست تو حالت موبایل

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#146]
![Screenshot 2024-09-10 122051](https://github.com/user-attachments/assets/8d002c8a-9f2d-4be4-8a6d-99ccd6d7cc29)
این قسمت زیاد جالب نیست تو حالت موبایل

**Comment by ali-josheghani** [comment]
این قبلا ایشو شده 

سپاس اینو میبندم
