### ISSUE TITLE
تو حالت 660px زمانی که به فوتر میرسی اسکرول عمودی ایجاد میشه

### ISSUE THREAD

**Issue by yaser-front-dev** [SalamLang/Salam-Website#148]
![Screenshot 2024-09-10 124020](https://github.com/user-attachments/assets/9d131413-449b-4344-8331-06771b4276f9)
تو حالت 660px زمانی که به فوتر میرسی اسکرول عمودی ایجاد میشه

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/911b9b53-2d65-4e33-92e2-d3f7a89537c6)
overflow x شد hidden
