### ISSUE TITLE
تکمیل بخش دارک مود

### ISSUE THREAD

**Issue by ali-josheghani** [SalamLang/Salam-Website#149]
https://github.com/SalamLang/Salam-Website/issues/145

**Comment by BaseMax** [comment]
مونده

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/4a7ad1ee-784e-435f-96f0-6cd03a297ad5)


![image](https://github.com/user-attachments/assets/1a488e6a-8865-447a-a1a4-4e7731820a4c)
