### ISSUE TITLE
نمیشه روی سه تا ایتم منو که توی سمت چپ هستن کلیک کرد

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#15]
![menu](https://github.com/user-attachments/assets/5f1db4c8-fd47-4ca3-b411-8012ea719079)
نمیشه روی سه تا ایتم منو که توی سمت چپ هستن کلیک کرد

**Comment by mohamadreza1388** [comment]
مشکل از زد ایندکس منو بود زیرا یک عکس روی ان افتاده بود و نمیشد روی ان کلیک کرد و حالا درست شد

**Comment by BaseMax** [comment]
سپاس از حل

**Comment by BaseMax** [comment]
تست بشه اگه اوکی بود این ایشو بسته شود. ارادت

**Comment by ali-josheghani** [comment]
fixed!
