### ISSUE TITLE
نسخه pwa نصبی نیست. کافه بازار رو سایتش رو چک بکنید چکار کرده. فکر کنم حتی محدود به موبایل کردن با سایت باز بشه نمیشه. چک کنید

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#150]
نسخه pwa نصبی نیست. کافه بازار رو سایتش رو چک بکنید چکار کرده. فکر کنم حتی محدود به موبایل کردن با سایت باز بشه نمیشه. چک کنید

**Comment by ali-josheghani** [comment]
https://bpi.ir/fa

**Comment by BaseMax** [comment]
باید توی موبایل هم تست کنیم

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/d1156770-69fb-4541-a9d8-ea1530de058e)

**Comment by ali-josheghani** [comment]
تایتل ها م اصلاح شد
