### ISSUE TITLE
کلا کاراکتر ها در این سکشن  بی نظم و خراب هستند و مورد بعدی اینکه فلش قاطی شده با بقیه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#151]
کلا کاراکتر ها در این سکشن  بی نظم و خراب هستند و مورد بعدی اینکه فلش قاطی شده با بقیه

![image](https://github.com/user-attachments/assets/b1b33915-69eb-4645-b27f-2d7865104b5c)

**Comment by ali-josheghani** [comment]
قراره تو فیگما این بخش ریدیزاین بشه

**Comment by BaseMax** [comment]
دیشب انجام داده فیگما رو اپدیت داده

**Comment by ali-josheghani** [comment]
done ✔️
