### ISSUE TITLE
فاصله اینها همه یکجور بشه مثل فاصله راست و چپ کل کانتینر

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#152]
فاصله اینها همه یکجور بشه مثل فاصله راست و چپ کل کانتینر
![image](https://github.com/user-attachments/assets/4aefda3b-c126-4a3e-9b9b-fbcd43eeee65)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/2b51af9b-a983-4be3-b78f-f5be92f8de45)

**Comment by BaseMax** [comment]
فاصله پایین بازم یکم کمتر بشه بنظرم تا برابر بالا بشه
