### ISSUE TITLE
بین فلش و باکس یک فاصله زیادی هست که مناسب نیست بهتره مناسب تر بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#155]
بین فلش و باکس یک فاصله زیادی هست که مناسب نیست بهتره مناسب تر بشه
![image](https://github.com/user-attachments/assets/c7e0b8d7-c451-43df-90fe-2d01c05db11f)

**Comment by ali-josheghani** [comment]
این قبلا توی ایشو های قبلی تایید شده ولی اگه نیاز بود دوباره باز شه
