### ISSUE TITLE
اسلایدر لوگو اسپانسر ها یا شرکت ها بهتره از بالا پاین خودکار وسط تنیم بشه جوری که نظم بیشتری بگیره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#156]
اسلایدر لوگو اسپانسر ها یا شرکت ها بهتره از بالا پاین خودکار وسط تنیم بشه جوری که نظم بیشتری بگیره
![image](https://github.com/user-attachments/assets/40804167-e394-42b7-9b2c-8933a78a4f25)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/63e4b531-e757-47a0-8802-a1ea9a2b3912)
