### ISSUE TITLE
در سکشن ما بهترین هارو داریم: یک اسم طولانی و اسم کوتاه مدل های مختلفی تست کنید ببینید چطوری میشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#157]
در سکشن ما بهترین هارو داریم: یک اسم طولانی و اسم کوتاه مدل های مختلفی تست کنید ببینید چطوری میشه

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/42a9aed9-6f9b-4d61-9fb2-abb7d3a79098)
✅
