### ISSUE TITLE
اون کاراکتر اونجا کلا بهم ریخته هم بی ریخت شده هم ابعاد و نسبت اندازه خرابه بنظر

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#159]
اون کاراکتر اونجا کلا بهم ریخته هم بی ریخت شده هم ابعاد و نسبت اندازه خرابه بنظر

![image](https://github.com/user-attachments/assets/85377430-f9ec-46a9-bf42-218221f26f08)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/a79216d1-ffc8-4484-b9bd-7d1970f8ec44)

fixed
