### ISSUE TITLE
ایتم های منو از وزن کمی برخوردارن و مانند طرح نیستند

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#16]
![menu2](https://github.com/user-attachments/assets/2def3f1e-e1a3-460a-9239-35dac14b1304)
**ایتم های منو از وزن کمی برخوردارن و مانند طرح نیستند**

**Comment by BaseMax** [comment]
بررسی شود

**Comment by ali-josheghani** [comment]
fixed
