### ISSUE TITLE
وقتی صفحه دانلود مستقیم باز میشه باید بازم تشخیص سیستم عامل بدیم ولی الان بنظر کلا نمیدیم. و اینکه باید فایل زبان رو دانلود بکنه این فانکشن اضافه بشه که فایل رو دانلود بکنه و یا کاربر رو هدایت بکنه به دانلود کردن لینک یا روشی که همه سایت ها انجام میدهند بعد چند ثانیه هدایت می کنند اینطوری هم صفحه نشون میدیم هم فایل دانلود میشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#160]
وقتی صفحه دانلود مستقیم باز میشه باید بازم تشخیص سیستم عامل بدیم ولی الان بنظر کلا نمیدیم. و اینکه باید فایل زبان رو دانلود بکنه این فانکشن اضافه بشه که فایل رو دانلود بکنه و یا کاربر رو هدایت بکنه به دانلود کردن لینک یا روشی که همه سایت ها انجام میدهند بعد چند ثانیه هدایت می کنند اینطوری هم صفحه نشون میدیم هم فایل دانلود میشه

https://salamlang.ir/download

**Comment by ali-josheghani** [comment]
اضافه شد در صورت نیاز دوباره باز کنید
