### ISSUE TITLE
عنوان صفحه های ۴۰۴ خطا مناسب نیست و انگلیسیه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#163]
عنوان صفحه های ۴۰۴ خطا مناسب نیست و انگلیسیه

مثل:
https://salamlang.ir/190197.txt

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/b3bb0d41-0235-46f2-a817-6503ff4d2bb0)

من چیز انگلیسی نمیبینم:

**Comment by BaseMax** [comment]
title tag

**Comment by ali-josheghani** [comment]
ok
