### ISSUE TITLE
خطای بیلد بخاطر وجود داشتن کد ساماندهی در فوتر

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#165]
خطای بیلد بخاطر وجود داشتن کد ساماندهی در فوتر

این کد اصلی هست که دادند:

```
 <img referrerpolicy='origin' id = 'rgvjjzpenbqenbqefukzfukz' style = 'cursor:pointer' onclick = 'window.open("https://logo.samandehi.ir/Verify.aspx?id=372266&p=xlaojyoeuiwkuiwkgvkagvka", "Popup","toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30")' alt = 'logo-samandehi' src = 'https://logo.samandehi.ir/logo.aspx?id=372266&p=qftiyndtodrfodrfwlbqwlbq' />
```

خطاها:

```out: 24:9  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
out: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
out:    Collecting page data ...
out:    Generating static pages (0/7) ...
out:    Generating static pages (1/7) 
err: Error: Event handlers cannot be passed to Client Component props.
err:   {referrerPolicy: "origin", id: ..., style: ..., onClick: function onClick, alt: ..., src: ...}
err:                                                            ^^^^^^^^^^^^^^^^
err: If you need interactivity, consider converting part of this to a Client Component.
err:     at ek (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140566)
err:     at Object.toJSON (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
err:     at stringify (<anonymous>)
err:     at eP (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
err:     at eE (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
err:     at AsyncLocalStorage.run (node:async_hooks:338:14)
err:     at Timeout._onTimeout (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:150397)
err:     at listOnTimeout (node:internal/timers:569:17)
err:     at process.processTimers (node:internal/timers:512:7) {
err:   digest: '1982491531'
err: }
err: Error: Event handlers cannot be passed to Client Component props.
err:   {referrerPolicy: "origin", id: ..., style: ..., onClick: function onClick, alt: ..., src: ...}
err:                                                            ^^^^^^^^^^^^^^^^
err: If you need interactivity, consider converting part of this to a Client Component.
err:     at ek (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140566)
err:     at Object.toJSON (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
err:     at stringify (<anonymous>)
err:     at eP (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
err:     at eE (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
err:     at Timeout._onTimeout (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
err:     at listOnTimeout (node:internal/timers:569:17)
err:     at process.processTimers (node:internal/timers:512:7) {
err:   digest: '237510[84](https://github.com/SalamLang/Salam-Website/actions/runs/10821514674/job/30023663558#step:4:85)86'
err: }
err: Error: Event handlers cannot be passed to Client Component props.
err:   {referrerPolicy: "origin", id: ..., style: ..., onClick: function onClick, alt: ..., src: ...}
err:                                                            ^^^^^^^^^^^^^^^^
err: If you need interactivity, consider converting part of this to a Client Component.
err:     at ek (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140566)
err:     at Object.toJSON (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
err:     at stringify (<anonymous>)
err:     at eP (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
err:     at eE (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
err:     at Timeout._onTimeout (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
err:     at listOnTimeout (node:internal/timers:569:17)
err:     at process.processTimers (node:internal/timers:512:7) {
err:   digest: '23751084[86](https://github.com/SalamLang/Salam-Website/actions/runs/10821514674/job/30023663558#step:4:87)'
```

**Comment by ali-josheghani** [comment]
fixed
