### ISSUE TITLE
صفحه دانلود باید نو ایندکس بشه الان داره صفحه های دنالود هر سیستم عامل تو گوگل ایندکس میشه اشتباهه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#166]
صفحه دانلود باید نو ایندکس بشه الان داره صفحه های دنالود هر سیستم عامل تو گوگل ایندکس میشه اشتباهه

https://salamlang.ir/download
و ..

https://www.google.com/search?q=site%3Asalamlang.ir&rlz=1C1GCEA_enIR1084IR1084&oq=site%3Asalamlang.ir&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRhAMgYIAhBFGDrSAQgyNDM1ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8

**Comment by BaseMax** [comment]
```
For "noindex":

<META NAME="robots" CONTENT="noindex">

For "nofollow":

<META NAME="robots" CONTENT="nofollow">

For both "noindex" and "nofollow":

<META NAME="robots" CONTENT="noindex,nofollow">


```

**Comment by ali-josheghani** [comment]
added
