### ISSUE TITLE
داخل صفحه ادیتور داخل مودال یک باگ داریم وقتی تب اول هستیم یا تب دوم تفاوت ایجاد میشه فاصله تب ها از بالا کلا جابجا داره میشه. کاری به فاصله پایین ندارم بیشتر مد نظرم فاصله تب ها از بالا هست که نباید تکون بخوره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#167]
داخل صفحه ادیتور داخل مودال یک باگ داریم وقتی تب اول هستیم یا تب دوم تفاوت ایجاد میشه فاصله تب ها از بالا کلا جابجا داره میشه. کاری به فاصله پایین ندارم بیشتر مد نظرم فاصله تب ها از بالا هست که نباید تکون بخوره

![image](https://github.com/user-attachments/assets/1b7167e9-0f39-474a-8d7d-161678786e8f)

![image](https://github.com/user-attachments/assets/57d8c21f-8b70-4e79-8926-e46aad5e35d9)

**Comment by ali-josheghani** [comment]
fixed
