### ISSUE TITLE
اینجا دو تا مشکل هست یکی اینکه بی نظمی توی کاراکتر هست هست دوم اینکه اون فلش وسط کاراکتر ها گم شده ودیده نمیشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#168]
اینجا دو تا مشکل هست یکی اینکه بی نظمی توی کاراکتر هست هست دوم اینکه اون فلش وسط کاراکتر ها گم شده ودیده نمیشه

![image](https://github.com/user-attachments/assets/697789c4-3bcb-44b3-a513-bea7dc529d41)

**Comment by ali-josheghani** [comment]
این ی ایشو مثل همین داره پس اینو میبندم سپاس
