### ISSUE TITLE
توی سکشن شماره موبایل وقتی خطا رخ میده و خطا ظاهر میشه ارتفاع سکشن جابجا میشه و زیاد میشه بهتره حل بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#169]
توی سکشن شماره موبایل وقتی خطا رخ میده و خطا ظاهر میشه ارتفاع سکشن جابجا میشه و زیاد میشه بهتره حل بشه

![image](https://github.com/user-attachments/assets/9d7f27b1-f631-4ff6-8ee6-adbb589775a1)

**Comment by ali-josheghani** [comment]
فیکس
