### ISSUE TITLE
اندازه منو ایتمی که فعال است کوچک است 

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#17]
![active-item](https://github.com/user-attachments/assets/4959e5fc-e9af-4cea-93eb-72b4e0ea9fbd)
منو ایتم فعال اندازه کوچک تری دارد نسبت به طرح و باید بزرگ شود

**Comment by BaseMax** [comment]
بررسی شود

**Comment by ali-josheghani** [comment]
fixed!
