### ISSUE TITLE
رنگ پس زمینه تولتیپ با فلشش رو بنظرم دقیقا یک رنگ بکنید الان یکم یکجوریه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#170]
رنگ پس زمینه تولتیپ با فلشش رو بنظرم دقیقا یک رنگ بکنید الان یکم یکجوریه

![image](https://github.com/user-attachments/assets/d0166271-6408-4a24-b502-19beac27757a)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/2e3c7581-919c-4dd0-8717-9de7c455adc3)
