### ISSUE TITLE
ایکن ها رنگش بنظرم خام خام سیاه نباشه یکم نقره ای باشه مثل ایکن ضربدر؟؟؟ 

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#174]
![image](https://github.com/user-attachments/assets/18d8476b-c3b3-4a15-905a-f407f0ca1649)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/6c2cb849-1536-4939-8942-d34f3a942bc2)
