### ISSUE TITLE
صفحه دانلود چرا تو لپ تاپ نصرالله اسکرول میخوره نباید بخوره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#176]

**Comment by ali-josheghani** [comment]
خب المنت نیاز به اسکرول داشته احتمالا برای اینکه بقیه رو ببینی اگه مایل باشین اسکرولشو میبندم

میشه عکس بدین؟

**Comment by BaseMax** [comment]
@mohamadreza1388

**Comment by BaseMax** [comment]
?

**Comment by ali-josheghani** [comment]
هروقت این مشکل دوباره اومد این ایشو رو باز کنید
