### ISSUE TITLE
اندازه لوگو با طرح همخوانی ندارد

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#18]
![logo](https://github.com/user-attachments/assets/2bad6df1-c611-4a2b-9e7b-47e9b31f57c1)
در طرح اندازه لوگو برابر با 196 در 196 پیکسل اما در سایت برابر با 160 در 160 پیکسل است

**Comment by BaseMax** [comment]
اندازه ها پیکسلی لزوما مهم نیست چون سایت ریسپانسیو هست

ولی سعی کنید نسبت چیز هارو توی سایت های مختلف رعایت کنید

سپاس
