### ISSUE TITLE
یک سکشن وجود ندارد

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#19]
![section1](https://github.com/user-attachments/assets/412c2ac0-a5a9-4bd9-9135-205fdcfd8d00)
این سکشن که بعد از سکشن کد است وجود ندارد

**Comment by BaseMax** [comment]
بنظر ساده میاد میشه اضافه اش کرد.

**Comment by ali-josheghani** [comment]
added!
