### ISSUE TITLE
یک بخش که مربوط به اجرای کد هست فرق داره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#20]
![code-runner](https://github.com/user-attachments/assets/6771dcab-087b-4a43-834b-79133533f9cc)
![code-runner2](https://github.com/user-attachments/assets/dfcc7d2b-f9d8-422f-bb99-faad30872e5d)
این دو سکشن باهم فرق دارن

**Comment by ali-josheghani** [comment]
این طبیعی نیست انقد فرق داشته باشه

شاید قبلا اون دولوپر ک اینجوری زده تایید شده که از ui نزده

چک شه لطفا

**Comment by ali-josheghani** [comment]
منتظر خبرم

**Comment by ali-josheghani** [comment]
پاسخی داده نشد میبندم نیاز بود دوباره باز کنین
