### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam-Website#204]
Seen here:

https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203

**Comment by BaseMax** [comment]
‍```
Run npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-config-next@1[4](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:5).2.13
npm error Found: eslint@9.10.0
npm error node_modules/eslint
npm error   dev eslint@"^9" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.4.0" from @typescript-eslint/utils@8.6.0
npm error     node_modules/@typescript-eslint/utils
npm error       @typescript-eslint/utils@"8.6.0" from @typescript-eslint/eslint-plugin@8.6.0
npm error       node_modules/@typescript-eslint/eslint-plugin
npm error         @typescript-eslint/eslint-plugin@"^[5](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:6).4.2 || ^6.0.0 || ^7.0.0 || ^8.0.0" from eslint-config-next@14.2.13
npm error         node_modules/eslint-config-next
npm error       1 more (@typescript-eslint/type-utils)
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.10.0
npm error   [6](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:7) more (@typescript-eslint/eslint-plugin, ...)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^[7](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:8).23.0 || ^8.0.0" from eslint-config-next@14.2.13
npm error node_modules/eslint-config-next
npm error   dev eslint-config-next@"14.2.13" from the root project
npm error
npm error Conflicting peer dependency: eslint@[8](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:9).57.1
npm error node_modules/eslint
npm error   peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.13
npm error   node_modules/eslint-config-next
npm error     dev eslint-config-next@"14.2.13" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/2024-0[9](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:10)-20T11_57_35_100Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-09-20T11_57_35_[10](https://github.com/SalamLang/Salam-Website/actions/runs/10958788598/job/30429758647?pr=203#step:4:11)0Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by jbampton** [comment]
Fixed thanks
