### ISSUE TITLE
این اسلایدر کلا مشکل داره شاید بخاطر دایرکشن اش باشه که خرابه با تاچ جابجا می کنی کلا خراب میشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#210]
![image](https://github.com/user-attachments/assets/3d7c2123-0720-42cd-a5d9-ca4db7806163)

**Comment by BaseMax** [comment]
Max Base, [9/26/2024 1:41 PM]
اسلایدر پایینی مشکل نداره

Max Base, [9/26/2024 1:41 PM]
اون سبزه مشکل داره انگار فقط

Max Base, [9/26/2024 1:41 PM]
نمونه های مختلف ببین. بخاطر dir نیست؟

Max Base, [9/26/2024 1:41 PM]
میتونی dir اون سکشن رو ltr بدی.

**Comment by ali-josheghani** [comment]
fixex
