### ISSUE TITLE
وقتز از صفحه اصلی میاد تو یه صفحه دیگه و لایوت جابجا میشه تم کلا میپره و از سر تصمیم گیری میشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#211]
![image](https://github.com/user-attachments/assets/1927374f-2851-4e52-a56d-b6f3e9188246)

![image](https://github.com/user-attachments/assets/a2bb0bad-fa6a-4eaf-b754-4b953851dd1b)

**Comment by ali-josheghani** [comment]
fix
