### ISSUE TITLE
این ایتم اولی توی صفحه حمایت توی تم دارک خراب بنظر میاد

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#212]
![image](https://github.com/user-attachments/assets/8682d134-9fe4-48bb-b6e9-da5fc7dd04f4)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/f87bc4c6-aa1a-4970-a83f-d6703cae4f4c)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/cf08656f-27fb-47f5-ad62-d119eb30450b)
