### ISSUE TITLE
لینک شده به صفحه اول

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#214]
![image](https://github.com/user-attachments/assets/53aa7aeb-a998-41b5-9ab4-bbce155639b8)

**Comment by BaseMax** [comment]
𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/22/2024 2:20 PM]
به کجا لینک بشه؟

Max Base, [9/22/2024 2:20 PM]
به سکشن بعدی؟

𝙰𝚕𝚒 𝙹𝚘𝚜𝚑𝚎𝚐𝚑𝚊𝚗𝚒, [9/22/2024 2:20 PM]
اها اسکرول بخوره یعنی

Max Base, [9/22/2024 2:20 PM]
جوری که با ثابت بودن هدر باز هم به ابتدای سکشن بعدی لینک بشه

Max Base, [9/22/2024 2:20 PM]
اره بنظر.

**Comment by ali-josheghani** [comment]
fix
