### ISSUE TITLE
فاصله از کنار

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#216]
![image](https://github.com/user-attachments/assets/85643033-f80b-43c5-90e1-9614d1178074)

**Comment by BaseMax** [comment]
Max Base, [9/22/2024 3:48 PM]
فاصله کمه باید یکم بیشتر بشه

Max Base, [9/22/2024 3:48 PM]
متن ها چسبیده به تمام گوشه ها

Max Base, [9/22/2024 3:48 PM]
باید چند پیکسل کم هم شده فاصله داشته باشه

**Comment by ali-josheghani** [comment]
Max Base, [9/22/24 3:48 PM]
عکس داره

Max Base, [9/22/24 3:48 PM]
فاصله کمه باید یکم بیشتر بشه

Max Base, [9/22/24 3:48 PM]
متن ها چسبیده به تمام گوشه ها

Max Base, [9/22/24 3:48 PM]
باید چند پیکسل کم هم شده فاصله داشته باشه

**Comment by ali-josheghani** [comment]
تو این سایز باید فونت کوچیک شه بنظرم

**Comment by ali-josheghani** [comment]
چون اگه فاصله بگیره میره خط بعدی متن ها و زشت میشه

**Comment by ali-josheghani** [comment]
نظرتون؟

**Comment by BaseMax** [comment]
ربطی نداره. یکم متن رو کوچک تر بکن خب

**Comment by ali-josheghani** [comment]
منم همینو میگم خب

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/0de0726c-2b0c-4e9f-b654-2d04ccd24b72)

**Comment by ali-josheghani** [comment]
نیاز بود ایشو باز شه لطقا
