### ISSUE TITLE
شماره موبایل انگار ارسال نمیشه یا فرم سابمیت نمیشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#219]
![image](https://github.com/user-attachments/assets/3e72a95b-0dfe-49ce-9d08-f6fb513106a5)

**Comment by BaseMax** [comment]
@soheilkhaledabdi سهیل اگه علاقه مند بودی میتونی روی وبسرویس این کار کنی.

توی نسخه اولیه که با پی اچ پی بود زده شده.
ولی توی نسخه جدید که با لاراول هست زده نشده.

مخزن قدیمی:
https://github.com/SalamLang/Salam-API

مخزن جدید:
https://github.com/SalamLang/Salam-Auth



ارادت

**Comment by ali-josheghani** [comment]
```javascript
import axios from "axios";

const baseURL = "https://auth.salamlang.ir/api/mobile";

const instance = axios.create({
  baseURL,
});

// instance.defaults.timeout = 2500;

export default instance;
```

دامنه گذاشته شد تا سهیل چک کنه
