### ISSUE TITLE
این صفحه حامی ها فاصله از پایین بنظر نداره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#220]
![image](https://github.com/user-attachments/assets/d7341a4d-ba74-4995-affc-945c6d9c21dd)

**Comment by BaseMax** [comment]
فاصله از پایین درست نیست
![image](https://github.com/user-attachments/assets/72a7d411-e876-4876-a2e3-38ac6a89d7d5)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/8d7f771d-58d9-4fb8-837d-aaff8d22cdd9)


از بالا و پایین فاصله یکسانی دارند
