### ISSUE TITLE
صفحه حمایت توی موبایل باید اول متن الویت باشه اول متن رو کامل نشون بده و بعد لیست لینک به حامی ها رو لیست کنیم پشت سر هم بدون فاصله با فاصله های یکسان

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#221]
![image](https://github.com/user-attachments/assets/4911b506-3d28-4976-bb2c-1274b3103d2b)

**Comment by ali-josheghani** [comment]
این تو ایشو های قبلی فیکس شده

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/fb87adc9-1c0e-49f7-92bc-c6969ee0394a)
