### ISSUE TITLE
صفحه حامی باگ داره داره دو تا اسکرول همزمان تو صفحه نشون میده

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#222]
![image](https://github.com/user-attachments/assets/aa10a7eb-3d27-430c-a933-7014808cf9b4)

**Comment by ali-josheghani** [comment]
خودتون چک کردید همچین موردی نبود

**Comment by BaseMax** [comment]
اگه نیست پس هیچی میبندیم.
