### ISSUE TITLE
عدد های داخل سایت عدد  ها هنوز انگلیسی هست. فونت رو تغییر ندادید که فارسی بشه؟ راهکار؟

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#224]
![image](https://github.com/user-attachments/assets/b3840d4b-52f8-4687-816c-0d19185efadb)

**Comment by ali-josheghani** [comment]
خب چون راهکاری اعلام نشد و فونتش اینجوری نبود دلیل بر این شد که اونایی که متنشون استاتیکن عددارو فارسی بزاریم و اونجایی که قابل تغیر نیست و داینامیکه با هندل تبدیل انجام بدیم که اینکار انجام شده

در صورت نیاز این ایشو رو باز کنین اگه دوباره عدد انگلیسی دیدید.
