### ISSUE TITLE
روی دکمه مودال که هاور میشم خیلی زوم و بزرگ میشه و میچسبه به گوشه ها که نباید اینقدر بچسبه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#225]
![image](https://github.com/user-attachments/assets/d953f987-e55c-452b-9dbe-fa20c7719485)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/1a62050b-ad7d-4800-bda8-9f2def17a406)
بزرگ شدنش یکم کم شد 

این الان هاور شدشه
