### ISSUE TITLE
تمام مودال هایی که همه جا داریم وقتی فعال و ظاهر میشه باید اسکرول صفحه غیر فعال و قفل بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#226]
![image](https://github.com/user-attachments/assets/a5fae2ef-5c6c-40c2-908f-f620550aadf4)

**Comment by ali-josheghani** [comment]
بقیه لاک میشدن گویا این مونده بود که اوکی شده در ایشو قبلی اگه نیاز بود در مورد مدالی که اسکرول داره ایشو زده بشه
