### ISSUE TITLE
بنظر وقتی مودال هم فعاله باز هدر روی صفحه میاد بنظرتون اوکی هست یا نه؟ تصمیم با خودت

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#227]
![image](https://github.com/user-attachments/assets/6933b3b7-3a9c-4c3d-93b6-cf2542adaa57)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/9d94d7a9-41fd-46aa-95c7-c7bb64255597)


جوری کردم که اصلا اسکرول نخوره منو بیاد اصلا

**Comment by ali-josheghani** [comment]
اسکرولشو وقتی مدال باز بود قفل کردم

**Comment by BaseMax** [comment]
اوکی.

هدر نباید روی مودال ظاهر بشه

**Comment by BaseMax** [comment]
هدر باید زیر لایه overlay گیر بکنه

**Comment by ali-josheghani** [comment]
ok
