### ISSUE TITLE
سلام صفحه داکیومنت رو هنوز کد نکردیم؟ فکر کنم کد کرده بودید ولی لینک اش رو ندارم بفرستید اگه زدید.

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#229]
سلام صفحه داکیومنت رو هنوز کد نکردیم؟ فکر کنم کد کرده بودید ولی لینک اش رو ندارم بفرستید اگه زدید.

**Comment by ali-josheghani** [comment]
هنوز کامل نشده ولی روتش هست :
/learn

**Comment by ali-josheghani** [comment]
این ایشو قبلا زده شده برای این مورد

**Comment by ali-josheghani** [comment]
پس میبندم و اگه صفحه تموم شد اونو مورد مخصوص رو میبندم
