### ISSUE TITLE
بنظر میرسه داخل تم دارک منو کناری موبایل زیرش بوردر پایین داره که توی تم لایت نیست بهتره هردو یکجور بشه و حاشیه تم دارک رو بردارید منظورم توی حالت نرمال هست کاری به هاور و اکتیو بودن ندارم کلیمیگم

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#233]
![image](https://github.com/user-attachments/assets/46d349d3-c560-4f68-b711-b3d05b040dc6)

![image](https://github.com/user-attachments/assets/138ca94e-62f1-47fe-862c-90b283ff2a91)

**Comment by BaseMax** [comment]
خلاصه: دارک رو مثل لایت بکنی.

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/5338c8d3-7c49-46c7-95c0-48065143f24c)
![image](https://github.com/user-attachments/assets/ff75bcf0-6946-45c9-8383-6517ab4d93f9)

**Comment by BaseMax** [comment]
بسته
