### ISSUE TITLE
تم دارک هست داخل صفحه اصلی این سکشن متن توضیح رنگ اش یکجوری هست خوب دیده نمیشه بهتر بهبود بدید

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#238]
![image](https://github.com/user-attachments/assets/d7d9a685-add1-48d4-b24b-da40ad71093b)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/2cffc18e-69e9-4645-ba32-6537bc2ed4d7)
