### ISSUE TITLE
صفحه حامی - این صفحه داخل این سایز خرابه چرا محتوا با فوتر قاطی میشه -  کلا تو این سایز ها که یک ستونه میشه بهتره چرا ما رو بیارید بالا اول صفحه بعد سایت های حاحمی همه زیر هم لیست بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#242]
![image](https://github.com/user-attachments/assets/f22872b1-66b2-4490-868e-9f6f67c0ebd1)

**Comment by BaseMax** [comment]
کلا تو این سایز ها که یک ستونه میشه بهتره چرا ما رو بیارید بالا اول صفحه بعد سایت های حاحمی همه زیر هم لیست بشه

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/7bb9ca40-6e3c-4618-b1be-5fd5f5cf4ad1)
