### ISSUE TITLE
صفحه اصلی یادگیری و داکیومنت نباید بالاش اینقدر بچسبه به هدر باید یکم فاصله داشته باشه. فاصله بالا پایین چپ راست همه برابر

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#244]
![image](https://github.com/user-attachments/assets/1acc80ec-19c6-47b7-a053-d5fd85e8f1c9)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/d5b54956-56f9-47ad-920a-a9695aacd646)
