### ISSUE TITLE
اضافه کردن کد اینماد به فوتر موقت تا بعد

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#245]
```
<a referrerpolicy='origin' target='_blank' href='https://trustseal.enamad.ir/?id=529005&Code=Gx6PecZik5vUpVJkVsATqoYQS1NADBAc'><img referrerpolicy='origin' src='https://trustseal.enamad.ir/logo.aspx?id=529005&Code=Gx6PecZik5vUpVJkVsATqoYQS1NADBAc' alt='' style='cursor:pointer' code='Gx6PecZik5vUpVJkVsATqoYQS1NADBAc'></a>
```

**Comment by ali-josheghani** [comment]
اینو ک قبلا اضافه کردیم مگه اون قبلیه نیست؟
‍‍‍```javascript

"use client";

import Image from "next/image";
import React from "react";

const InteractiveImage = ({
  src,
  alt,
  id,
  referrerPolicy = "no-referrer",
  onClick,
  style,
  ...attr
}) => {
  return (
    <Image
      referrerPolicy={referrerPolicy}
      id={id}
      style={style}
      onClick={onClick}
      alt={alt}
      src={src}
      {...attr}
    />
  );
};

export default InteractiveImage;
        <InteractiveImage
          referrerPolicy="no-referrer"
          id="rgvjjzpenbqenbqefukzfukz"
          style={{ cursor: "pointer" }}
          onClick={() =>
            window.open(
              "https://logo.samandehi.ir/Verify.aspx?id=372266&p=xlaojyoeuiwkuiwkgvkagvka",
              "Popup",
              "toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30"
            )
          }
          alt="logo-samandehi"
          src="https://logo.samandehi.ir/logo.aspx?id=372266&p=qftiyndtodrfodrfwlbqwlbq"
          width={50}
          height={50}
        />

```

**Comment by BaseMax** [comment]
نه قبلی نیست فرق می کنه اونم بزار باشه

**Comment by ali-josheghani** [comment]
بزنم باشه؟

**Comment by ali-josheghani** [comment]
ایشو رو ببندم؟

**Comment by BaseMax** [comment]
اضافه کنید این یک کد جدید هست. علاوه بر قبلی اضافه بشه.

بعد ببندید

**Comment by BaseMax** [comment]
کاربر گرامی لوگو خود را کپی کرده بدون تغییر در سایت خود قراردهید و لطفا به این نکته توجه داشته باشد که ممکن است لوگو شما به محض بارگذاری در سایت نمایان نشود و نمایان شدن آن طی 24 ساعت آینده انجام پذیرد. خواهشمند است 24 ساعت صبر نمایید چانچه پس از گذشت 24 ساعت نمایان نشد تیکت ارسال نمایید.

**Comment by ali-josheghani** [comment]
<div className="w-auto h-auto flex justify-center items-center gap-3">
          <InteractiveImage
            referrerPolicy="no-referrer"
            id="rgvjjzpenbqenbqefukzfukz"
            style={{ cursor: "pointer" }}
            onClick={() =>
              window.open(
                "https://logo.samandehi.ir/Verify.aspx?id=372266&p=xlaojyoeuiwkuiwkgvkagvka",
                "Popup",
                "toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30"
              )
            }
            alt="logo-samandehi"
            src="https://logo.samandehi.ir/logo.aspx?id=372266&p=qftiyndtodrfodrfwlbqwlbq"
            width={50}
            height={50}
          />
          <a
            referrerPolicy="origin"
            target="_blank"
            href="https://trustseal.enamad.ir/?id=529005&Code=Gx6PecZik5vUpVJkVsATqoYQS1NADBAc"
          >
            <Image
              width={50}
              height={50}
              referrerPolicy="origin"
              src="https://trustseal.enamad.ir/logo.aspx?id=529005&Code=Gx6PecZik5vUpVJkVsATqoYQS1NADBAc"
              alt="enmad"
              style="cursor:pointer"
              code="Gx6PecZik5vUpVJkVsATqoYQS1NADBAc"
            />
          </a>
        </div>


دوتا اضافه شد

**Comment by ali-josheghani** [comment]
بنظرم تا ۲۴ دیگه اوکی نشد اینو باز کنیم مجدد
