### ISSUE TITLE
ایکن فلش داخل دکمه با متن خیلی چسبیده باید یکم بیشتر فاصله بگیره. با تمام دکمه های دیگه سایت مقایسه و بررسی کن

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#246]
![image](https://github.com/user-attachments/assets/3b7f35b7-457f-47f8-8dbf-042a75fe6c33)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/47d88f90-6ca5-440e-8137-cf8fc24e3b73)

**Comment by BaseMax** [comment]
خیلی دکمه های مختلفی داریم هر کدوم یک فاصل متفاوتی داره تمام دکمه هارو یکسان سازی کنید

**Comment by ali-josheghani** [comment]
ok
