### ISSUE TITLE
صفحه حامی. فاصله از چپ صفره از راست فاصله بیشتره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#247]
![image](https://github.com/user-attachments/assets/ef8f9429-cd28-40b8-9be4-a32da733e162)

**Comment by BaseMax** [comment]
https://salamlang.ir/supporter

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/9846a6e7-7de4-47db-8621-d1f438c57a44)
