### ISSUE TITLE
توی تم دارک سیاه ها باید نقره ای طوسی چیزی بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#249]
توی تم دارک سیاه ها باید نقره ای طوسی چیزی بشه

![image](https://github.com/user-attachments/assets/7491f75d-b0ef-497f-a9f1-5458a5ef14ca)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/6e58a590-292d-4160-913b-07c521467ffb)
