### ISSUE TITLE
چپ چین کردن فیلد ارسال شماره  - حالا تغییر دادن رنگ ها و مناسب سازی کردن اونها

### ISSUE THREAD

**Issue by ali-josheghani** [SalamLang/Salam-Website#250]

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/eecb739d-3f5d-4500-a6d4-9ca9416de690)

**Comment by BaseMax** [comment]
علاوه بر حل اون مشکلی که حل کردید بنظرم این اصلا رنگ های خوبی نداره متن های داخل بنظر دیده نمیشه. توی دارک اینطوری خراب شده؟ بررسی شود

**Comment by BaseMax** [comment]
رنگ متن داخل فیلد نباید هم رنگ با پس زمینه خود فیلد باشه

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/38404a97-77dd-4e60-afbd-8f5993100d7a)
