### ISSUE TITLE
تغییر رنگ ارور فیلد شماره 

### ISSUE THREAD

**Issue by ali-josheghani** [SalamLang/Salam-Website#252]
![image](https://github.com/user-attachments/assets/c2c93231-61a3-4abd-9b0f-afd8576dcdf7)
این نگ به تم سایت نمیخوره

**Comment by ali-josheghani** [comment]
چه رنگی بزاریم؟

**Comment by BaseMax** [comment]
این مورد رو من نگفتم. بنظر اقای ابراهیمی گفته.

صحبت شد: بهتره فقط از رنگ های خود پروژه استفاده بشه. نزدیک نارنجی هم میشه

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/f665e6ec-01b1-430d-81f8-560126d023fd)

**Comment by ali-josheghani** [comment]
سپاس
