### ISSUE TITLE
توی حالت شب چرا ایکنش ماه نیست بنظر الان یه دایره فقط گذاشتیم منطقی تره اگه ماهش کنیم نه؟

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#264]
![image](https://github.com/user-attachments/assets/3141800f-dd2f-4101-b08e-838299115895)

**Comment by ali-josheghani** [comment]
نه این باید ماه بشه فک کنم پکیجش باگ داره و بعضی وقتا این مشکل پیش میاد

بجای پکیج کاستوم بسازم؟

**Comment by ali-josheghani** [comment]
کاستوم ساختم
