### ISSUE TITLE
وقتی خارج از منو یعنی داخل محیط سایت کلیک و تاچ می کنیم منو خودکار بسته نمیشه بنظرم بهتره اینطوری باشه یعنی تمام منو و سایت های دنیا اینطورری هستند

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#266]
وقتی خارج از منو یعنی داخل محیط سایت کلیک و تاچ می کنیم منو خودکار بسته نمیشه بنظرم بهتره اینطوری باشه یعنی تمام منو و سایت های دنیا اینطورری هستند
![image](https://github.com/user-attachments/assets/c73eb65e-ae11-4b0a-9ed2-b6feb7491161)

**Comment by ali-josheghani** [comment]
فیکس شد

**Comment by ali-josheghani** [comment]
قبلا اینجور بود ولی گویا ی مشکل پیش اومده بود ک فیکش شد
