### ISSUE TITLE
ایکن ماه توی حالت موبایل هنوز خرابه و داره دایره نشون میده باید ماه باشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#269]
![image](https://github.com/user-attachments/assets/3f0d4801-962e-41f3-8d93-6020e11f4b8f)

**Comment by ali-josheghani** [comment]
خودم کاستوم زدم این پکیجه که قبلا حذف شده

**Comment by ali-josheghani** [comment]
تغیرات اومده بالا و این مشکل وجود نداره
