### ISSUE TITLE
اون خط سفید هست و خیلی سفیده بهتره یکم نقره ای تر باشه بخصوص داخل این حالت تم دارک

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#271]
![image](https://github.com/user-attachments/assets/7203b2af-03d9-4c43-8d89-62f67edf64ec)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/ff8cdf5c-89b1-4794-8500-d29f971d9344)
