### ISSUE TITLE
خطا در بیلد نشدن و اپدیت نشدن سایت - ./src/app/(without-footer)/learn/page.jsx Module not found: Can't resolve '../../../../../public/svgs/dooble-emoji.svg'

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#275]
root@maxbasecode:/var/www/html/salamlang.ir# bun run build
$ next build
  ▲ Next.js 15.0.0
  - Experiments (use with caution):
    · forceSwcTransforms

   Creating an optimized production build ...
Failed to compile.

./src/app/(without-footer)/learn/page.jsx
Module not found: Can't resolve '../../../../../public/svgs/dooble-emoji.svg'

https://nextjs.org/docs/messages/module-not-found

> Build failed because of webpack errors
error: script "build" exited with code 1

**Comment by ali-josheghani** [comment]
چون سایت تغییرات جدیدش اومد بالا
