### ISSUE TITLE
توی تم دارک اون ایکن تیره هست دیده نیمشه بنظرم اشتباهه باید رنگش چیز دیگه باشه توی دارک حداقل

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#277]
![image](https://github.com/user-attachments/assets/a52f4cab-994c-4524-80e1-77f4db048e22)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/ee629369-2018-4032-8f17-02d4ecb16061)
