### ISSUE TITLE
مشکل داریم توی فاصله ها

### ISSUE THREAD

**Issue by arshiartwork** [SalamLang/Salam-Website#281]
![image](https://github.com/user-attachments/assets/ef3697b5-210a-40e9-9547-b41e36bf2c12)
توی این قسمت فاصله ها یکسان نیستن و یک فریمی دورش هس ک خوب نیس.

**Comment by ali-josheghani** [comment]
متوجه نشدم بیشتر توضیح میدی عرشیا؟

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/1c1a7ab4-698a-4522-ad93-f79c60efbfef)
fixed

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/d588bbce-4373-4d12-b10d-62f71a01e387)
fixed

**Comment by arshiartwork** [comment]
<img width="1280" alt="isue" src="https://github.com/user-attachments/assets/e81ec4c7-99f1-4d64-aafe-8b8c313b6b15" />
مشکل داریم فاصله های کناری با فاصله ای اون ایکن های جابه جایی یکی نیستن

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/e388f1bf-cb98-4d45-b3af-d2c941ec83dc)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/debd3f0c-940d-4398-8248-ab1afd420411)
