### ISSUE TITLE
We should use `lowercase` filenames and folders

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam-Website#3]
File naming should be consistent and all lowercase if possible.

The website files should be lowercase

**Comment by erfangnu** [comment]
I think it's normal to use upper case and capital case for Component files in the react ecosystem. not?

**Comment by jbampton** [comment]
https://github.com/SalamLang/Salam-Website/tree/main/public

**Comment by erfangnu** [comment]
okay right we need to fix it.

**Comment by MAGNET-CODE** [comment]
Ok, finally, I will convert all the files to lowercase letters

**Comment by BaseMax** [comment]
@ali-josheghani please check

**Comment by BaseMax** [comment]
این گفته که اسم فایل و پوشه ها باید حرف کوچک باشه

منظور فایل های اینجا هست https://github.com/SalamLang/Salam-Website/tree/main/public

کاری به کامپوننت های ری اکتتون ندارم

**Comment by BaseMax** [comment]
یکسری فایل هم نام گذاری درست نداره مثل https://github.com/SalamLang/Salam-Website/blob/main/public/22.png که عدد هست اگه نیازه اسمشون اصلاح و تمیز بشه

بقیه فایل های پروژه هم اگه اسمشون هنوز کوچک نیست کوچک بشه

اگه هم تمومه ایشو رو ببندید.

**Comment by BaseMax** [comment]
@jbampton thanks and done
