### ISSUE TITLE
صفحه نباید اسکرول دار بشه الان دو تا اسکرول باهم داریم

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#62]
![image](https://github.com/user-attachments/assets/317036a8-3b9f-406d-a217-f1e82ef6339f)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/700220da-d342-42a9-88e8-70a95e21ea87)
من چک کردم نبود

**Comment by ali-josheghani** [comment]
اگه باز دیده شد این ایشو رو باز شه لطفا!
