### ISSUE TITLE
لوگو داخل منو کناری موبایل بی کیفیت هست. ایکن سه خط برای موبایل هم بی کیفیت هست

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#63]
![image](https://github.com/user-attachments/assets/f0e25905-c6d8-4d9b-b246-da2ae7e6c1c8)

![image](https://github.com/user-attachments/assets/05f90433-263b-42ce-a367-4e5bab93a91b)

**Comment by ali-josheghani** [comment]
fixed
