### ISSUE TITLE
یکسری خطا هم داریم نیمدونم حل کردیم یا خیر.

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#64]
یکسری خطا هم داریم نیمدونم حل کردیم یا خیر.

![image](https://github.com/user-attachments/assets/dc57c7fd-c2ce-4a24-9204-d798077d9158)

**Comment by ali-josheghani** [comment]
ارور key ها برطرف شد اروری دیکه ای ندیدم
