### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#71]
root@maxbasecode:/var/www/html/salamlang.ir# npm run build

> next-app@0.1.0 build
> next build

  ▲ Next.js 14.2.4

   Creating an optimized production build ...

 ✓ Compiled successfully

Failed to compile.

./src/components/common/Modal.tsx
47:13  Error: Component definition is missing display name  react/display-name
53:16  Error: Component definition is missing display name  react/display-name
57:14  Error: Component definition is missing display name  react/display-name
63:16  Error: Component definition is missing display name  react/display-name

./src/components/molecules/KeyPressFullScreen.jsx
26:6  Warning: React Hook useEffect has a missing dependency: 'setIsHidden'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
root@maxbasecode:/var/www/html/salamlang.ir#

**Comment by ali-josheghani** [comment]
fixed
