### ISSUE TITLE
از پایین فاصله ای نداره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#72]
![image](https://github.com/user-attachments/assets/874e26b4-c4d2-4592-969c-c96a83f5accb)
به پایین چسبیده به نظرم بهتره فاصله داشته باشه

**Comment by BaseMax** [comment]
کلا بنظر میرسه که حتی اون گیف شکلک دست هم خراب شده و کشیده شده
نباید اینطوری بشه

**Comment by ali-josheghani** [comment]
فاصله از فیکس شد ممنون از فیدبک 


و میمونه ی سوال اون گیف برا من مشکل نداره 
احساس می کنم خطای دیده وقتی گیف انیمیشنش و فریمش میخواد بچرخه اسکرین گرفتی

**Comment by BaseMax** [comment]
سپاس اگه تمومه ایشو رو ببندید

**Comment by ali-josheghani** [comment]
اوکیه

**Comment by ali-josheghani** [comment]
اگه نیاز بود دوباره باز شه
