### ISSUE TITLE
اینجا م همینطور از پایین فاصله نداره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#73]
![image](https://github.com/user-attachments/assets/f036d186-59cd-4400-820d-c089504822d7)
بنظر بهتره فاصله داشته بااشه از پایین

**Comment by ali-josheghani** [comment]
این رو میتونیم دو حالت بکنیم یا اسکرول یا scale شو کم کنیم یعنی کوچیک تر شه تو این سایز 

کدوم بظرت؟ من بازم دوتا رو انجام میدم

مرسی بابت فید بک

**Comment by ali-josheghani** [comment]
فیکسه

چک شه لطفا

**Comment by BaseMax** [comment]
ممنون اگه حل شده ایشو رو ببندید

**Comment by BaseMax** [comment]
حل شد؟

**Comment by ali-josheghani** [comment]
yes
