### ISSUE TITLE
ادیتور توی موبایل کار نمیکنه

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#74]
![image](https://github.com/user-attachments/assets/c7e730c9-cfe7-4929-8242-0e2c7611d55f)

**Comment by ali-josheghani** [comment]
منظورت یعنی دکمه run نیستش؟

**Comment by mohamadreza1388** [comment]
چرا منظورم همونه

**Comment by mohamadreza1388** [comment]
اشتباه زسوندم شرمنده

**Comment by ali-josheghani** [comment]
رواله پس 

نه اوکیه خواهش می کنم 

سپاس

**Comment by josheghani-copilet** [comment]
چک بشه لطفا

**Comment by ali-josheghani** [comment]
چک بشه لطفا

**Comment by mohamadreza1388** [comment]
دکمه ران توی موبایل نیست همچنان

**Comment by ali-josheghani** [comment]
اوه شرمنده من پوش نکردم 

sorry

**Comment by mohamadreza1388** [comment]
یه مشکلی دارم البته نمیدونم دست چیه
![Screenshot (28)](https://github.com/user-attachments/assets/330b2f5b-f5d2-4376-ae64-1dea1719fc20)
نمیتونم اسکرول کنم

**Comment by mohamadreza1388** [comment]
@ali-josheghani

**Comment by BaseMax** [comment]
اره این مشکل اسکرول رو قبلا یه ایشو براش زده بودم.
چون چند تا اسکرول همزمان تو صفحه هست. یکی برای کل صفحه. یکی برای خود ادیتور

**Comment by mohamadreza1388** [comment]
خود اقای جوشقانی گفتن که شما گفتید اسکرول بسته بشه توی این صفحه 
البته اگه اشتباه نفهمیده باشم

**Comment by ali-josheghani** [comment]
این بخاطر min height هست که تو کلاساش داده شده و باید حذف بشه و درست بشه

**Comment by ali-josheghani** [comment]
به هرحال این ایشو مربوط به اسکرول نیست و جدا زده شده 

این ایشو اوکی کردم اگه مشکلی داخلش نیست ببندیم

**Comment by BaseMax** [comment]
ببندید پس

**Comment by ali-josheghani** [comment]
مجدد نیاز بود باز بشه  مجدد این ایشو

reopen issues
