### ISSUE TITLE
خط دوم نمیرع

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#75]
![image](https://github.com/user-attachments/assets/b9b46087-3214-48ad-be71-d7132aa9fc65)
هرچی بنویسی توی خط 1 هست
یه مشکل دیگه هم وجود داره وقتی تب زده میشه باید توی ادیتور اندازه یه تب بره جلو اما روی یه المنت دیگه فوکوس میشه
منم این مشکلو داشتم با کد زیر حلش کردم
```js
document.querySelector('.editor').addEventListener('keydown', function (event) {
    if (event.key === 'Tab') {
        event.preventDefault();
        const textarea = this;
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        textarea.value = textarea.value.substring(0, start) + '\t' + textarea.value.substring(end);
        textarea.selectionStart = textarea.selectionEnd = start + 1;
    }
});
```

**Comment by ali-josheghani** [comment]
خب هنوز سراغ ادیتور نرفتیم فعلا داریم استاتیک رو پیاده سازی می کنیم 
وگرنه خیلی ریزه کاری داره از حمله همین TAB 


دوم برای اینکه این باگ وقتی متن طولانی مینویسی یا کد طولانی اصلا نباید بره خط بعد و باید حالت اسکرول باشه تو ادیتور هم اینجوریه اسکرول از سمت x


مرسی بابت فید بک

**Comment by ali-josheghani** [comment]
اینم فیکس شد الان پوش میشه

به اصطلاحی text nowarp اضافه شده تا متن ها شکسته نشه و نره خط بعدی 
چون محیط ادیتور اینجور نیست و دوطرف اسکرول میخوره

**Comment by BaseMax** [comment]
پشتیبانی از کلید تب هم هندل شد؟ اگه نشده یک ایشو جدید جدا برایش بسازید یادتون نره

**Comment by ali-josheghani** [comment]
ساخته شد سپاس

**Comment by ali-josheghani** [comment]
این ایشو رو میبندم اگه مشکلی بود باز لطفا باز بشه سپاس
