### ISSUE TITLE
عنوان همه صفحه ها اصلاح بشه و متن درست قرار نگیره نه متن انگلیسی

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#76]

**Comment by ali-josheghani** [comment]
ی تمپلتی برای نمونه میدید ؟

مثلا 

سلام | ادیتور 

سلام | آموزش 

.... 

همینجوری باشه؟

**Comment by BaseMax** [comment]
صفحه اصلی:
زبان برنامه نویسی سلام | یک توضیح مختصر و کوتاه
مثل:
زبان برنامه نویسی سلام | برنامه نویسی برای همه


صفحه های دیگه هم:

درباره ما - زبان سلام

دانلود زبان سلام - برنامه نویسی سلام

آزمایش آنلاین زبان سلام - برنامه نویسی سلام

**Comment by ali-josheghani** [comment]
ok ty

**Comment by ali-josheghani** [comment]
done
