### ISSUE TITLE
دکمه بزن بریم ایکن نداره انگار ایکنش حذف یا مخفی شده

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#79]
![image](https://github.com/user-attachments/assets/be613b74-deac-4ca4-bffb-fc8a718108be)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/c48aeabc-8c93-4ed7-80d2-103686397b3e)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/c48aeabc-8c93-4ed7-80d2-103686397b3e)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/59bdfb5a-65b2-431e-950a-a09f26d0377d)
