### ISSUE TITLE
ایکنی که برای ویژگی های زبان استفاده شده بی کیفیت وعکس هست. باید وکتوری و اس وی جی بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#80]
نمونه مثال
http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Frtl.44b23a12.png&w=96&q=75

![image](https://github.com/user-attachments/assets/b46cd147-ae21-4d01-849c-084d2ade8a9b)

![image](https://github.com/user-attachments/assets/0a0337dc-4131-413a-8ff7-2ff7bb424b9a)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/11ebeec2-8ec1-4301-8013-f73c77307b23)
