### ISSUE TITLE
اینجا توی اسلایدر سه تا گروه بندی شده ولی مشخص نیست کدوم گروه الان اکتیو و فعال هست درسته که اون که اندازه اش بزرگ تره اکتیو هست ولی بهتره یک تغییر رنگی هم بینشون باشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#82]
اینجا توی اسلایدر سه تا گروه بندی شده ولی مشخص نیست کدوم گروه الان اکتیو و فعال هست درسته که اون که اندازه اش بزرگ تره اکتیو هست ولی بهتره یک تغییر رنگی هم بینشون باشه

![image](https://github.com/user-attachments/assets/fad31e67-ffab-456a-a8f0-e69781c5f0a9)

**Comment by ali-josheghani** [comment]
fixed
