### ISSUE TITLE
روی هر ادم و اواتار میریم باید تولتیب ظاهر بشه که داخل تولتیب اسم اون شخص نمایش داده بشه. فقط هم اسم میزاریم فامیلی نیاز نیست که خیلی طولانی نشه زیر ۲۰ کاراکتر نهایت

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#83]
روی هر ادم و اواتار میریم باید تولتیب ظاهر بشه که داخل تولتیب اسم اون شخص نمایش داده بشه. فقط هم اسم میزاریم فامیلی نیاز نیست که خیلی طولانی نشه زیر ۲۰ کاراکتر نهایت

![image](https://github.com/user-attachments/assets/9a9a504c-8436-4099-941a-a91e21bc3a67)

**Comment by ali-josheghani** [comment]
تو هاور تولتیپ بیاد؟

**Comment by BaseMax** [comment]
بله هاورش

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/b8c7b79e-4624-4360-bd58-b74881fd346c)
