### ISSUE TITLE
ایکن موبایل داخل فیلد شماره موبایل بنظرم خود ایکن خیلی تیره هست یکم کم رنگ تر بشه شاید بهتر باشه نیاز نیست حتما سیاه خام باشه نظرت؟

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#84]
![image](https://github.com/user-attachments/assets/e0ce2874-4927-4e93-a5f2-3e5a5c8ef3e4)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/30f6315a-3302-4c3b-9961-6c38ea264728)
