### ISSUE TITLE
فیلد شماره موبایل فرمش باگ داره وقتی رو دکمه میزنی علاوه بر اینکه دکمه هم بزرگ و کشیده میشه حتی کل سکشن و فیلد موبایل هم داره کشیده و بزرگ میشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#85]
فیلد شماره موبایل فرمش باگ داره وقتی رو دکمه میزنی علاوه بر اینکه دکمه هم بزرگ و کشیده میشه حتی کل سکشن و فیلد موبایل هم داره کشیده و بزرگ میشه

![image](https://github.com/user-attachments/assets/8b4671e8-cdb7-4c24-ac33-f4490db8d713)

**Comment by ali-josheghani** [comment]
fixed
