### ISSUE TITLE
منو باز میشه خیلی مشکل داره قاطی میشه محتوا ها

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#86]
![image](https://github.com/user-attachments/assets/36107310-52d6-48f1-b999-d9e69cdf11e7)

**Comment by ali-josheghani** [comment]
مشکل z-index باشه احتمالا

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/f0a3a9cb-4d14-4c44-be8d-70566c6a8916)
