### ISSUE TITLE
وقتی صفحه کوچک باشه و منو باز بشه بعد صفحه رو بزرگ بکنید کلا دیگه اسکرول صفحه وجود نداره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#87]
مرحله اول:
کوچک کردن صفحه

![image](https://github.com/user-attachments/assets/7548ccdc-0c63-4844-a92b-50f9e91d926f)

مرحله دوم: باز کردن منو
![image](https://github.com/user-attachments/assets/4ffa7aa3-866f-4fe4-974d-5fd2dd0456d8)

مرحله سوم: بزرگ کردن صفحه نمایش کامپیوتر حالا اسکرول کل صفحه قفل شده و اسکرولی دیگه وجود نداره و کلا امکان جابجایی نیست.

![image](https://github.com/user-attachments/assets/38a30a4f-42cf-4acd-9be0-7b49a545faa7)

**Comment by ali-josheghani** [comment]
fixed
