### ISSUE TITLE
فاصله بالا و پایین هر ایتم faq باید یکجور باشها لان یکجور نیست فاصله بالا زیاده و فاصله پایین کم بهتره زیاد بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#88]
فاصله بالا و پایین هر ایتم faq باید یکجور باشها لان یکجور نیست فاصله بالا زیاده و فاصله پایین کم بهتره زیاد بشه

![image](https://github.com/user-attachments/assets/5521443c-48ec-4098-9493-bd034ce68af1)

**Comment by BaseMax** [comment]
Max Base, [9/7/2024 2:12 PM]
فاصله هارو درست کنید

Max Base, [9/7/2024 2:13 PM]
خرابه هنوز

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/029e5c73-d7e5-41ed-a005-7c39c2bbeab0)

![image](https://github.com/user-attachments/assets/abdbb809-9c3a-4b67-872e-9a904b210c11)
