### ISSUE TITLE
رنگ یکسری عناصر فرق داره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#89]
![Screenshot (1)](https://github.com/user-attachments/assets/7d63575b-8b38-419d-8d2b-40f24ff94e47)
![Screenshot (2)](https://github.com/user-attachments/assets/78cee4a7-874e-4567-82c7-0d2fecdd04e7)
این دو رنگ هایشون فرق داره

**Comment by ali-josheghani** [comment]
fixed
