### ISSUE TITLE
داخل تنظیمات ادیتور هم روی ۳ تا ایتم بالا هم ۶ تا پایین روی هر کدوم روی هر کدوم کلیک بشه ۲ ثانیه تاخیر داره تا انیمیشن و حالت اکتیوش شروع بشه این تاخیر زیاده باید سریعترش کرد

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#91]
داخل تنظیمات ادیتور هم روی ۳ تا ایتم بالا هم ۶ تا پایین روی هر کدوم روی هر کدوم کلیک بشه ۲ ثانیه تاخیر داره تا انیمیشن و حالت اکتیوش شروع بشه این تاخیر زیاده باید سریعترش کرد

![image](https://github.com/user-attachments/assets/1ad97381-7dbb-4eea-8bd1-5c699cfc98d5)

**Comment by ali-josheghani** [comment]
گویا چک کردم و همچین موردی نبود 
اگه دوباره مشاهده شد این ایشو باز بشه
