### ISSUE TITLE
رنگ متن ها فرق داره

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#92]
علاوه بر اینکه رنگشون فرق داره عکس های بکگراند و همچنین ایموجی هم فرق داره
![Screenshot (2)](https://github.com/user-attachments/assets/5423ec4a-efa8-42a4-ac80-78ff3ed7e773)
![Screenshot (1)](https://github.com/user-attachments/assets/8680eac6-e117-4871-9e96-7b3f76f88170)

**Comment by ali-josheghani** [comment]
fixed
