### ISSUE TITLE
داخل تنظیمات ادیتور وقتی نسخه رو تغییر میدیم جای باکس و کامپوننت سلکت باکس نسخه ها هم کلا داره جابجا میشه که باگه و اشتباهه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#93]
داخل تنظیمات ادیتور وقتی نسخه رو تغییر میدیم جای باکس و کامپوننت سلکت باکس نسخه ها هم کلا داره جابجا میشه که باگه و اشتباهه

![image](https://github.com/user-attachments/assets/4fc6bc1f-5b45-4c90-b3f9-a03bc9a88c6f)

**Comment by ali-josheghani** [comment]
اگه منظورتون اینه ک وقتی نسخه رو تغییر میدی پوزیشن دکمه تغییر میکنه رو اونو اوکی کردم
