### ISSUE TITLE
ناحیه کلیک خور جهت بستن مودال ها رو بیشتر کنید الان فقط وقتی رو سه تا دایره زده بشه بسته میشه روی اطراف دایره ها زده بشه بسته نمیشه این نیازه که پینگ و قسمت های چپ و پایین بالاش هم کامل اینطوری بشه حتی نوکش هم زدن بخوره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#94]
ناحیه کلیک خور جهت بستن مودال ها رو بیشتر کنید الان فقط وقتی رو سه تا دایره زده بشه بسته میشه روی اطراف دایره ها زده بشه بسته نمیشه این نیازه که پینگ و قسمت های چپ و پایین بالاش هم کامل اینطوری بشه حتی نوکش هم زدن بخوره
![image](https://github.com/user-attachments/assets/5765a9ae-4874-4266-ac12-42c5e42ef798)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/2a4bc600-8669-413c-96e0-01e717686893)

**Comment by ali-josheghani** [comment]
fixed
