### ISSUE TITLE
داخل موبایل یا تبلت که سکشن کد داخل ادیتور پس زمینه میگیره باید فاصله اش از بالا چپ راست همه یکجور باشه ولی الان اینطوری نیست و فاصله بالا بیشتر از فاصله راست چپ هست

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#95]
داخل موبایل یا تبلت که سکشن کد داخل ادیتور پس زمینه میگیره باید فاصله اش از بالا چپ راست همه یکجور باشه ولی الان اینطوری نیست و فاصله بالا بیشتر از فاصله راست چپ هست

![image](https://github.com/user-attachments/assets/1d7dafae-7f42-44aa-9dcf-73ddc7c51163)

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/93c4bbb5-5254-4e85-8588-3207cbcfbbf3)

**Comment by BaseMax** [comment]
Max Base, [9/8/2024 12:57 PM]
این چرا ارتفاع کامل نگرفته

Max Base, [9/8/2024 12:58 PM]
باید کل ثصفحه رو بگیره خودکار 100vh بشه

**Comment by BaseMax** [comment]
![image](https://github.com/user-attachments/assets/72b80a73-8b61-405f-9f8f-9abdd542cfa6)

یعنی اینکه اینقدر نباید پایین صفحه خالی و سفید بیوفته توی موبایل یا حتی سیستم
باید کل صفحه رو محیط کد بگیره
