### ISSUE TITLE
مشکل جزئی کارت ها

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Website#96]
![Capture](https://github.com/user-attachments/assets/2fd92031-d230-4410-b162-3347f552ac67)
![Capture2](https://github.com/user-attachments/assets/a9dfec7d-548c-4c79-8375-d8e8f4ecfbf6)
ااولی مال طرح و دومی مال سایته
اندازه و وزن فونت ها کمی فرق داره به نظرم
عرضشون هم فرق داره

**Comment by ali-josheghani** [comment]
![image](https://github.com/user-attachments/assets/0d35fde0-84ae-4755-9976-a79d4e456ab0)
اصلاح شد 
بازم اگه مشکلی داشت این ایشو رو باز کنید 
سپاس
