### ISSUE TITLE
داخل موبایل تبلت وقتی ادیتور رو میبینی کلا باگ داره و نمیشه کامل اسکرول کرد. شاید هم چند تا اسکرول همزمان داریم یک اسکرول داخل محیط نوشتن کد هست ولی خارج اون هم یک دکمه شیر هست که بعد ادیتور افتاده و کلا نمیشه بهش دسترسی پیدا کرد و مشکل اسکرول توی صفحه شدید  داریم

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#97]
داخل موبایل تبلت وقتی ادیتور رو میبینی کلا باگ داره و نمیشه کامل اسکرول کرد. شاید هم چند تا اسکرول همزمان داریم یک اسکرول داخل محیط نوشتن کد هست ولی خارج اون هم یک دکمه شیر هست که بعد ادیتور افتاده و کلا نمیشه بهش دسترسی پیدا کرد و مشکل اسکرول توی صفحه شدید  داریم

![image](https://github.com/user-attachments/assets/19c3e5ba-cc66-4021-98e1-a99f2b0d491b)

**Comment by ali-josheghani** [comment]
fixed
