### ISSUE TITLE
برای بستن مودال کپی لینک هم فقط رو دایره ها کلیک بکنیم بسته میشه باید یکم فضای کلیک خور رو بیشتر کنیم اطلاف دکمه های دایره هم زدن بسته بشه

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#98]
برای بستن مودال کپی لینک هم فقط رو دایره ها کلیک بکنیم بسته میشه باید یکم فضای کلیک خور رو بیشتر کنیم اطلاف دکمه های دایره هم زدن بسته بشه

![image](https://github.com/user-attachments/assets/1818d2b9-a19c-48d2-a4d7-88a2321c109f)

**Comment by ali-josheghani** [comment]
fixed
