### ISSUE TITLE
صفحه ادیتور طول کاستوم اسکرول بنظرم زیاده یکم کمتر ونازک تر بشه بهتره

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#99]
صفحه ادیتور طول کاستوم اسکرول بنظرم زیاده یکم کمتر ونازک تر بشه بهتره

![image](https://github.com/user-attachments/assets/01e43847-a8f7-4f22-a445-a12783bff8e3)

**Comment by BaseMax** [comment]
این خوب شده:
![image](https://github.com/user-attachments/assets/efaa9f0c-2f87-46d0-ac1d-225a5127f864)

**Comment by ali-josheghani** [comment]
fixed
